name: Update Main Branch

on:
  push:
    branches:
      - test

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest commit message
        id: get-commit-message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Check if commit message contains "V:"
        id: check-message
        run: |
          if [[ "${{ env.COMMIT_MESSAGE }}" == V:* ]]; then
            echo "MERGE=true" >> $GITHUB_ENV
          else
            echo "MERGE=false" >> $GITHUB_ENV
          fi

      - name: Merge test branch to main
        if: env.MERGE == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout main
          git merge test --no-ff -m "Merge test branch into main"
          git push origin main
